### PR TITLE
adding social share buttons

### PR DESCRIPTION
**Pull request by ellisonleao**
ref #17

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @ellisonleao – many thanks for the PR. But I think this is not exactly what #17 suggested:

> After creating the button, it shares a short sentence about the project, website URL and hashtag #VítimasDaIntolerância.

You PR adds the share buttons per story, sharing the story's URL, not the project URL with it's own description. Following that we might not need a per story/case set of share buttons, but a single set on the header, or maybe before/after the list of cases, or yet in the footer…

What do you think about it?

**Comment by ellisonleao** [comment]
Oh sorry, i thought we were adding sharing buttons per story along with the project's hashtag. Do you prefer just a set of social share links on the footer then? Also, do you have any preferred sentence to be added as the share text?

**Comment by cuducos** [comment]
Worry not : ) As we pick up the _main_ story randomly, I wouldn't share the link to one story. It might be better to create a URL per case and share the case URL listing all stories… but this is a topic for another/issue PR I guess.

Regarding the short description,I think it could be something we already use, such as _Conheça os ataques motivados por intolerância política_ ; )

**Comment by turicas** [comment]
If we're going to put share buttons I vote to share the case, not a specific story about it.

**Comment by ellisonleao** [comment]
@cuducos @turicas what about adding a new url for the case with all the stories related to it for and use that new url on the share buttons?

something like:

`/case/:slug` or just `/:slug`

> If we're going to put share buttons I vote to share the case, not a specific story about it.

that is the current behaviour no? i've added the `case.main_story.url` as the share link

**Comment by cuducos** [comment]
>  what about adding a new url for the case with all the stories related to it for and use that new url on the share buttons?

I like the idea, and I'd go for `/:slug` for the sake of simplicity ; )

> that is the current behaviour no? i've added the `case.main_story.url` as the share link

`case.main_story.url` is the URL of the main story (which isn't actually _main_, it's just one of the stories randomly pick from the pile; so I wouldn't give even more spotlight to it).

**Comment by turicas** [comment]
+1 for having a page for each case in `/:slug`.

**Comment by ellisonleao** [comment]
i can do that. Should we open a new issue for it?

**Pull request closed without merging**
