### PR TITLE
Mobile styles for #13

### PR DESCRIPTION
**Pull request by humrochagf**

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @humrochagf. I was just merging this branch now we have conflicts. 
Until 7f57363, commits are on `master` already. We have conflicts because we both edited the styles for the footer (I added  202b857 to `master`). Can you fix conflicts and let me know when you're done so I can properly code review and merge?

**Comment by cuducos** [comment]
BTW, my bad. I just re-read my previous message and it looks like more aggressive then I intended. I was just surprised that after pushing your comments plus  202b857 to `master` the PR hasn't shown itself as merged and thus I forgot the most important thing: a huge thank you for the collaboration, interest and stamina in working on this issue late night yesterday and early morning today ❤️

**Comment by humrochagf** [comment]
No problem, i will do the merge and fix the conflicts right now

**Comment by humrochagf** [comment]
@cuducos i fixed the conflicts and also changed the font approach to use a fluid font size math from https://css-tricks.com/snippets/css/fluid-typography/ so it will be better to read at any phone size

**Comment by cuducos** [comment]
Many thanks for advancing on this issue!

IMHO the current strategy over-complicated the CSS, @humrochagf. What about defining a style with this fluid-typography strategy **once** in the `body { … }` and then using `rem` to inherit this size in all other elements?

**Comment by humrochagf** [comment]
Yeah, i share this though. But i was thinking on do that on a second PR organizing it on maybe a sass structure to keep things on a kiss aproach

**Comment by cuducos** [comment]
We have a working mobile version online. I think there are two ways from now:

* Either we wait until this second PR with SASS and all the magic
* Or we wait for a fix in terms of complexity of the font sizer

I see no urgency to merge something that will bring technical debt in at this point.

**Comment by humrochagf** [comment]
@cuducos done! Thank you with the advises :heart:

**Comment by humrochagf** [comment]
Sorry, now its done :smile: forgot to check big displays

**Comment by cuducos** [comment]
Awesome ✨

**Pull request merged**
